### ISSUE TITLE
Weiterentwicklung/Änderung des Codes

### ISSUE THREAD

**Issue by Prinzpaulaner** [EIonTusk/jugendwortdesjahres_2020#3]
Moin @EIonTusk ,
Ich wollte mal fragen ob ich deinen Code in einem benutzerfreundliches Programm verwenden darf.
Ich will diesen Bot allen menschen auch ohne Programmierkenntnissem zur Verfügung stellen.
Natürlich wirst du auch in den Credits verlinkt.

Mit Schaebrnackischen Grüßen
Prinzpaulaner

**Comment by EIonTusk** [comment]
Salve @Prinzpaulaner ,

natürlich darfst du gerne den Code verwenden, insofern ich, wie von dir versprochen, im Programm als Quelle erwähnt werde. Ich werde aber vielleicht den Code noch etwas umstrukturieren, sodass man sich mit verschiedenen Proxy Servern verbinden kann. Außerdem geht es bald in eine neue Runde, weshalb ich den Bot wieder umschreiben muss. Nichtsdestotrotz bin ich sehr gespannt auf deine Arbeit und finde es toll, dass du   die Möglichkeit, mit dem Bot zu voten, weiteren Menschen eröffnen willst.

Schabernäckische Grüße zurück
EIonTusk

**Comment by EIonTusk** [comment]
Das zuvor geschriebene wurde durchgeführt.
